<h3 class="activity">
    Activité récente 
    <a href="<?php echo $this->url(array(), 'activity', true); ?>">(Voir toute l'activité)</a>
</h3>
<ul class="activity">
    <?php foreach ($this->activityItems as $item): ?>
    <?php $source = $item->getSource(); ?>
    <li>
        <div class="datetime">
            <?php echo $this->escape($item->publicationDate->toString('dd/MM HH:mm')); ?>
        </div>
        <div class="content">
            <a href="<?php echo $this->escape($item->link); ?>"
               title="<?php echo $this->escape($item->description); ?>">
                <?php echo $this->escape($item->title); ?>
            </a>
        </div>
        <div class="source">
            <a href="<?php echo $this->escape($source->getLink()); ?>"
               title="<?php echo $this->escape($source->getName()); ?>">
                <?php echo $this->escape($source->getName()); ?>
            </a>
        </div>
    </li>
    <?php endforeach; ?>
</ul>
<h3>Présentation</h3>
<p class="terminal">Ce site Internet a pour but de présenter mes travaux et activités de développement réalisés sur mon temps libre. Il a pour vocation de centraliser mon activité Internet provenant de plusieurs sources :</p>
<ul>
    <li>Twitter</li>
    <li>Mon blog developpez.com</li>
    <li>Mon compte Github</li>
    <li>Mon profil Viadeo</li>
</ul>
<p>Et d'autres sources à venir... Plus tard il pourra également servir à y héberger d'autres projets. Ce site est totalement en cours de construction et par conséquent très vide. Pour les curieux, vous pouvez suivre son avancement et consulter son code source sur <a href="http://github.com/lucascorbeaux/maitre-corbeaux.com" title="Dépôt Github de maitre-corbeaux.com">le dépôt Github</a>.</p>
