<h3>It's not a bug, it's a feature...</h3>
<h4><?php echo $this->message ?></h4>
<p>Si le problème persiste, contactez un administrateur.</p>
<?php if (isset($this->exception)): ?>
<h4>Exception :</h4>
<p>
    <strong>Message :</strong> <?php echo $this->exception->getMessage() ?>
</p>
<h4>Stack trace:</h4>
<pre>
<?php echo $this->exception->getTraceAsString() ?>
</pre>
<h4>Request Parameters:</h4>
<pre>
<?php echo var_export($this->request->getParams(), true) ?>
</pre>
<?php endif ?>
